### ISSUE TITLE
Add anti-spam filtering

### ISSUE THREAD

**Issue by keathley** [chadev/chatech-jobs#36]
We need to add anti-spam filtering for postings. The easiest thing to do is just to hook up [rakismet](https://github.com/joshfrench/rakismet) with our JobPosting model.

**Comment by t-richards** [comment]
If a job posting is determined to be spam by the external service, should it be rejected outright (no save, no nothing)?

Alternatively, we could allow the posting to be saved, but require an admin to manually "approve" the posting before it becomes visible on the frontend (this is a tiny bit more complicated).

**Comment by juzten** [comment]
I like the idea of admin approval if the service thinks the post is spam. We would also need to limit the number of posts by IP address otherwise we will be in the same boat, just on the admin side. 

If people don't want to do the admining, I don't mind at all being the person who  verifys and approves or deletes posts labeled as spam.

**Comment by t-richards** [comment]
Fixed in 8342c632fe2de4bedede0188134ad74d37b2a790
